language: ruby
services:
  - cassandra
before_install:
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - sudo service cassandra start
  - gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx
matrix:
  include:
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  allow_failures:
    # broken on travis
    - rvm: ruby-head
    - rvm: rbx
notifications:
  email:
    recipients:
      - dan.kubb@gmail.com
    on_success: never
    on_failure: change
