language: ruby
services:
  - cassandra
before_install:
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - sudo service cassandra start
  - gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head
  - rbx
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  allow_failures:
    # dm-core adapter spec occassionally fails on JRuby (i.e. Bignum too large
    # to convert to long)
    - rvm: jruby
    - rvm: jruby-head
notifications:
  email:
    recipients:
      - jabradford@gmail.com
    on_success: never
    on_failure: change
